language: node_js
node_js:
  - "5.4.0"
  - "5.3.0"
  - "5.2.0"
  - "5.1.1"
  - "5.1.0"
  - "5.0.0"

before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" == "5.4.0" ] ; then npm install -g npm@3.3.6; fi'
script:
  - "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- --ui bdd -R spec -t 5000"
after_script:
  - "npm install coveralls@2 && cat coverage/lcov.info | coveralls"